### ISSUE TITLE
Documentation Plans

### ISSUE THREAD

**Issue by Giodiro** [FalkonML/falkon#1]
This issue collects items of documentation which are missing & should be written.

## Example notebooks

- [ ] Sparse data
- [ ] GPU parameters
- [ ] Extending (e.g. extending the center-selection algorithm)

## Missing docstrings

 - LogisticFalkon is not documented
 - center_selection does not have a sphinx section
 - sparse module could be documented much better (many methods of SparseTensor are missing)

**Comment by jaiabhayk** [comment]
Import falkon gives the following error, any suggestions what is missing as I just followed the steps from the installation  ==>

sparse_helpers.so: undefined symbol: _ZN5torch3jit6tracer9addOutputEPNS0_4NodeERKN2at6TensorE

**Comment by Giodiro** [comment]
Hi @jaiabhayk , please open a new issue for this. I will follow-up here: https://github.com/FalkonML/falkon/issues/2
