### ISSUE TITLE
Enable CUDA in CI

### ISSUE THREAD

**Issue by Giodiro** [FalkonML/falkon#14]
We are stuck at 51% code coverage because CI does not have CUDA.

This requires more effort to install the library in the CI pipeline.

**Comment by mathurinm** [comment]
I am not 100 % sure, but I believe Travis does not have GPU instances. CircleCI has, but they are not free.

**Comment by Giodiro** [comment]
Maybe we could install jenkins on our local servers and then use smee:
https://www.jenkins.io/blog/2019/01/07/webhook-firewalls/

I'll have a go in the next few days

**Comment by Giodiro** [comment]
Maybe we could install jenkins on our local servers and then use smee:
https://www.jenkins.io/blog/2019/01/07/webhook-firewalls/

I'll have a go in the next few days
