### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by MrHuff** [FalkonML/falkon#32]
Hi!

Thank you for writing this library. It's very cool to finally be able to scale kernel regression to a billion points!

Running into the following:

RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support: 
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.

Thank you for the help!

Best regards,
Robert

**Comment by Giodiro** [comment]
Hi!

Are you trying to use it on a GPU? You should check that CUDA is installed properly, maybe you could try sending the output of `nvcc --version` 

Also try to delete the KeOps cache (if you are on ubuntu or similar you can run `rm -rf ~/.cache/pykeops*`) and run falkon again to force recompilation.

**Comment by MrHuff** [comment]
Hi,

NVCC version is 11.1. 

Tried clearing the pykeops cache, but it gave me the same error.

Maybe it pykeops doesn't support NVCC 11.1?

Thank you!

Best regards,
Robert

**Comment by MrHuff** [comment]
Hi,

After some debugging, it seems like pykeops wasn't able to detect my CUDA installation. 

-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- No CUDA support
-- Configuring done
-- Generating done

Closing this!

**Comment by MrHuff** [comment]
closed, found bug on my own

**Comment by Giodiro** [comment]
Great, happy you managed to fix it :)
