### ISSUE TITLE
ModuleNotFoundError: No module named 'falkon.sparse.sparse_helpers' when testing installation

### ISSUE THREAD

**Issue by cvignac** [FalkonML/falkon#38]
Hello, 

I followed the installation steps and did not run into any error while compiling the library.
However, when trying the kernel ridge regression notebook, I cannot load the module.

I get the following error trace:

>>> import falkon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vignac/falkon/falkon/__init__.py", line 3, in <module>
    from . import kernels, sparse, center_selection, preconditioner, optim
  File "/home/vignac/falkon/falkon/kernels/__init__.py", line 1, in <module>
    from .kernel import Kernel
  File "/home/vignac/falkon/falkon/kernels/kernel.py", line 6, in <module>
    from falkon.mmv_ops.fmm_cpu import fmm_cpu_sparse, fmm_cpu
  File "/home/vignac/falkon/falkon/mmv_ops/fmm_cpu.py", line 10, in <module>
    from falkon.sparse.sparse_tensor import SparseTensor
  File "/home/vignac/falkon/falkon/sparse/__init__.py", line 2, in <module>
    from .sparse_ops import sparse_norm, sparse_square_norm, sparse_matmul
  File "/home/vignac/falkon/falkon/sparse/sparse_ops.py", line 4, in <module>
    from falkon.sparse.sparse_helpers import norm_sq, norm_
ModuleNotFoundError: No module named 'falkon.sparse.sparse_helpers'

Is it just a path that is incorrect, or do you think it is a bigger problem with the installation?

Thanks,
Clement 

-----

Packages version:
nvcc: 11.4
g++: 7.5.0
cmake: 3.18.2

$ pip list
Package           Version
----------------- ------------
certifi           2021.10.8
cycler            0.11.0
falkon            0.6.3
joblib            1.1.0
kiwisolver        1.3.2
matplotlib        3.4.3
numpy             1.21.4
Pillow            8.4.0
pip               21.2.4
psutil            5.8.0
pykeops           1.4.2
pyparsing         3.0.5
python-dateutil   2.8.2
scikit-learn      1.0.1
scipy             1.7.2
setuptools        58.0.4
six               1.16.0
threadpoolctl     3.0.0
torch             1.10.0+cu113              (works fine on gpu)
typing-extensions 3.10.0.2
wheel             0.37.0

Installation traces: everything seemed to be fine:

$ pip install ./keops
Processing ./keops
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: numpy in /home/vignac/.conda/envs/falkon/lib/python3.9/site-packages (from pykeops==1.4.2) (1.21.4)
Building wheels for collected packages: pykeops
  Building wheel for pykeops (setup.py) ... done
  Created wheel for pykeops: filename=pykeops-1.4.2-py3-none-any.whl size=478011 sha256=dac861f7bd93a552854c4566aaf688a1deaaf737518a862f4818e04bc8b8d16d
  Stored in directory: /tmp/pip-ephem-wheel-cache-bq1e39qr/wheels/36/47/f5/4be78e0d60dfe330cfb4652a2e21c469d4f6ea7bb0d0d767df
Successfully built pykeops
Installing collected packages: pykeops
Successfully installed pykeops-1.4.2

$ pip install .
Processing /home/vignac/falkon
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: torch>=1.4 in /home/vignac/.conda/envs/falkon/lib/python3.9/site-packages (from falkon==0.6.3) (1.10.0+cu113)
Collecting scipy
  Downloading scipy-1.7.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.8 MB)
     |████████████████████████████████| 39.8 MB 5.5 MB/s 
Requirement already satisfied: numpy in /home/vignac/.conda/envs/falkon/lib/python3.9/site-packages (from falkon==0.6.3) (1.21.4)
Collecting scikit-learn
  Downloading scikit_learn-1.0.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (24.7 MB)
     |████████████████████████████████| 24.7 MB 108.8 MB/s 
Collecting psutil
  Downloading psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
     |████████████████████████████████| 293 kB 125.6 MB/s 
Requirement already satisfied: typing-extensions in /home/vignac/.conda/envs/falkon/lib/python3.9/site-packages (from torch>=1.4->falkon==0.6.3) (3.10.0.2)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Collecting joblib>=0.11
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Building wheels for collected packages: falkon
  Building wheel for falkon (setup.py) ... done
  Created wheel for falkon: filename=falkon-0.6.3-cp39-cp39-linux_x86_64.whl size=1270129 sha256=a55a9db44d82a77908f9c190aae18500e199d29563d74434bbeeff2ed977fe41
  Stored in directory: /tmp/pip-ephem-wheel-cache-qj6av2bg/wheels/42/2f/de/817b4dc8ce9bdfe9d8d5b31d82288a66442e83b0509995d8a1
Successfully built falkon
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, psutil, falkon
Successfully installed falkon-0.6.3 joblib-1.1.0 psutil-5.8.0 scikit-learn-1.0.1 scipy-1.7.2 threadpoolctl-3.0.0

**Comment by Giodiro** [comment]
Hi! This might be an easy fix: have you tried to import falkon from within the same folder where you installed it?

If so, try again from another folder! (Or if it's important to work in the same folder install with pip install --editable).
If not let me know and I'll look into it more

**Comment by cvignac** [comment]
Sorry, I forgot to answer!

 It indeed works if I run it inside the falkon folder. Does it mean that I am supposed to include all my code inside this folder as well?
