### ISSUE TITLE
Python version requirement?

### ISSUE THREAD

**Issue by mohamad-amin** [FalkonML/falkon#40]
What's the Python version requirement for Falkon? Is it 3.6? I haven't seen it mentioned anywhere but in [setup.py](https://github.com/FalkonML/falkon/blob/master/setup.py) I see that 3.6 is a requirement. Am I right?

Thanks.

**Comment by Giodiro** [comment]
Hi! It's actually 3.7 (minimum supported by PyTorch). The requirements are slightly messy right now, but you'll also need torch >= 1.9
