### ISSUE TITLE
Using custom kernels in Falkon

### ISSUE THREAD

**Issue by mohamad-amin** [FalkonML/falkon#41]
Hey, 

After checking [kernel.py](https://github.com/FalkonML/falkon/blob/master/falkon/kernels/kernel.py), I think it should be possible to write a custom kernel and use it in Falkon, but I'm not sure about the conditions under which I'll get proper speedups using my custom kernel. Let me elaborate on the kernel that I have:

Suppose that given a pair of datapoints `(x1, x2)`, my kernel is deterministic, meaning that I have a function to compute `k(x1, x2)` directly (not super fast, and not trivial to compute, but deterministic). Thus, I think in this case, no training (`.fit`) is needed in Falkon, am I right? Moreover, I'm not able to write the KeOps  routine to compute my kernel (thus, if I use `DiffKernel` as my parent class, I'm not able to write `_keops_mmv_impl`, and I have to set KeOps to False). 

I'd like to know if in such a case, do I need to compute the full `n^2` kernel matrix to compute the KRR predictions, or my space and time complexity will be `O(n sqrt(n))`?

P.S: In my case, kernel computation is expensive and I'd like to minimize the number of kernel computation calls.

Thanks for the great work!

**Comment by Giodiro** [comment]
Hi,
I recently did a lot of refactoring of the kernel classes. In particular there is a notebook on how to implement a custom kernel [https://falkonml.github.io/falkon/examples/custom_kernels.html] ! Try to pull from master and have a look, especially `kernel.py`. 

You do not need to use `DiffKernel` (unless you want the autodiff capabilities), but just `Kernel`.

You'll need to implement the `compute` function, which essentially takes a few data-points and computes a kernel matrix.

Let me know if you run into memory issues (that's the tricky bit I haven't expanded on in the notebook).

For KeOps support, you can also try to ask the KeOps people on gh. but note that if your data is high dimensional (d > 100) KeOps may not help much...
