### ISSUE TITLE
FixedSelector Center selection in Falkon Model

### ISSUE THREAD

**Issue by bananenpampe** [FalkonML/falkon#43]
Hello, 

I am trying to pass a FixedSelector instance to center_selection in the Falkon constructor, however, I do not obtain a different error to the default "Uniform" selector, which leads me to suspect that it uses the default instead.

This is the code I am using:

```python

indices_torch = torch.from_numpy(indices).reshape(-1,1)
X_centers_init = Xtrain[indices].clone()
Y_centers_init = Ytrain[indices].clone()

selector = FixedSelector(X_centers_init,Y_centers_init,indices_torch)

kernel = kernels.GaussianKernel(sigma=1.352)

model = Falkon(
    maxiter=100,
    kernel=kernel,
    penalty=1.07e-06,
    M=20000,
    center_selection=selector,
    options=options
        
)

```

Could you advise on what is going wrong here?

**Comment by Giodiro** [comment]
Hi!
Your code seems correct: it should be using the fixed selector.
Not sure what you mean that you do not obtain a different error. In general I don't expect big changes between uniform and fixed center selection, unless the fixed centers are chosen in some special way.

**Comment by bananenpampe** [comment]
Hi,

The points are chosen using furthest point sampling which is a strategy that works for my problem and is expected to improve error over a random selection for that specific problem. I wrote that issue because the error that I receive is identical to two digits for both selections which is not the expected behaviour

**Comment by Giodiro** [comment]
I see! That is indeed strange.

The code which switches between the default "uniform" strategy, and a user-provided strategy is at https://github.com/FalkonML/falkon/blob/554758902b9f31b3f6a4c86060c45b332a17ad37/falkon/models/model_utils.py#L64 -- and in your case it should simply use the provided selector. 

You can also try to print the nystrom points of the model (`model.ny_points_`) after fitting to check whether they are what you expect or not.

**Comment by bananenpampe** [comment]
Okay, I have checked with `torch.allclose(model.ny_points_,X_centers_init)` and the points are correctly set using a selector.

But, I still obtain the same errors to the fifth or sixth digit after the comma between uniform selector and my selection

**Comment by bananenpampe** [comment]
Hello, thank you very much for your input.
Eventually, it was due to an error in the pipeline that lead to incorrect normalization.
