### ISSUE TITLE
Failed to find C-extensions

### ISSUE THREAD

**Issue by cvignac** [FalkonML/falkon#44]
Hello, I wanted to reinstall Falkon on a linux server (because it cound not find Cuda). I deleted the environment and followed all the installation step again. 

Unfortunately, now I keep having the following error: 
"ImportError: Failed to find C-extension. Please recompile Falkon."

  - Is there a way for me to check if the extension is correctly installed, and where it is located?
  - Is there a way to force installation of these extension (I have tried deleting and reinstalling falkon with various pip options, but it did not make a difference).

Thanks a lot,

Clement

**Comment by Giodiro** [comment]
Hi Clement,
Could you check that you're not trying to import falkon from *within the falkon directory*?

After installing you should run python from another directory and import from there.

(btw if this is indeed the problem the easy way around it is to install in editable mode: `pip install -e`)

**Comment by cvignac** [comment]
Thank you Giodiro, that was indeed the issue. 

Installation with pip gave a  `OsError : undefined symbol: _ZN3c1012OptionalTypeC1ESt10shared_ptrINS_4TypeEE`.

What worked for me was:

```
conda create -n falkon python=3.9
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch      (rather than pip)
conda install Cython
conda install scipy                (I got an error when installing falkon before running this one)
pip install ./keops/
pip install .
```

I still have a problem because the gpu is not detected, but that's probably a keops issue.
