### ISSUE TITLE
ENH: build and deploy doc automatically when pushing/merging to master

### ISSUE THREAD

**Issue by mathurinm** [FalkonML/falkon#5]
Hi @Giodiro
I spent a bit of time to implement an automated doc deployment with CircleCI [in this PR on another repo](https://github.com/mathurinm/celer/pull/142) so if you want we can have a look at it together for this one. 

The config code is present in the PR I linked, apart from that you need to add a deploy key to github and circleCI as detailed in [Add a Github Deploy key here](https://circleci.com/docs/2.0/gh-bb-integration/)

**Comment by Giodiro** [comment]
I think we have it! I merged manually, but it's now in master.
Docs will be built only on master, or branches named doc-* or ci-* (this will probably change in the future).
