### ISSUE TITLE
Extracting a model's expansion coefficients

### ISSUE THREAD

**Issue by arthurfl** [FalkonML/falkon#51]
Hi, 

Is there a simple way to export the alphas out of a `falkon.Falkon` or `falkon.hopt.objectives` fitted model? 

thanks, 
Arthur

**Comment by Giodiro** [comment]
Hi Arthur,
from a `Falkon` object you should be able to read its `alpha_` attribute. 

From the hopt package it's not so simple since many things are recomputed at inference time, are you thinking of a particular objective?

Giacomo

**Comment by arthurfl** [comment]
Thanks Giacomo. I'm actually using a custom objective, but it's close in essence to `SGPR`.

**Comment by Giodiro** [comment]
In SGPR we're not saving parameters inside the model, but we always recompute them (even when calling predict), so there's no simple equivalent to alpha. Looking at the predict method of SGPR you could save `L`, `LB` and `c` and those could be considered your parameters.

**Comment by arthurfl** [comment]
I see. I might rewrite my objective function, in that case. I can see that with `HoldOut`, I think I can access the alphas from `HoldOut._calc_intermediate()`. 

thanks! 
Arthur
