### ISSUE TITLE
large M cases

### ISSUE THREAD

**Issue by ahabedsoltan** [FalkonML/falkon#52]
I was trying to try FALKON with M~256k,512k(number of centers). But the process gets killed. How can I efficiently apply FALKON in these large M cases?

**Comment by Giodiro** [comment]
The dependency of Nystrom-KRR on M is cubic-time, quadratic-memory -- you're probably running out of memory (512k = 976GiB). M should be small (order of sqrt(number of points).

What is your use-case? What are your data dimensions?
