### ISSUE TITLE
Failing to reproduce the Laplacian kernel computation

### ISSUE THREAD

**Issue by arthurfl** [FalkonML/falkon#57]
Hi, 

I'm trying to reproduce how falkon computes the Laplacian kernel, as I have to outsource some models I've optimized. So far I'm largely unsuccessful: I get consistent results between my python implementation and using sklearn's `metrics.pairwise.laplacian_kernel()`, but completely different results with `falkon.kernels.LaplacianKernel()`. 

It's hard to tell what's different in the falkon implementation, as I didn't find a simple way to access the `_sq_dist()` method used in `laplacian_core()`.  Is it really a Manhattan distance computed here? Is there any additional normalization? Would you have a simple numpy implementation which would reproduce falkon's results? 

thanks a lot, 
Arthur

**Comment by Giodiro** [comment]
Hi @arthurfl , you can try to have a look at the functions in 'falkon/tests/naive_kernels.py'. In particular, the numpy code for the Laplacian kernel is
```
import numpy as np
from scipy.spatial.distance import cdist
def naive_laplacian_kernel(X1, X2, sigma):
    pairwise_dists = cdist(X1, X2, 'euclidean')
    return np.exp(-pairwise_dists / sigma)
```
possibly the issue is that Falkon and sklearn have inverted parametrizations for the length-scale.

**Comment by arthurfl** [comment]
Thanks! Actually I'm using a vector length-scale (not compatible with sklearn's `metrics.pairwise.laplacian_kernel()`, or `naive_laplacian_kernel()`). Is `naive_diff_laplacian_kernel()` intended to reproduce this?

**Comment by Giodiro** [comment]
Yes, that should work!

**Comment by arthurfl** [comment]
All good now, thanks a lot!
